spring:
  profiles:
    active: test
---
server:
  port: 8202
---
spring:
  profiles: test #测试环境
  application:
    name: springcloud-study-config-client
---
eureka:
  client:
    service-url:
      defaultZone: eureka7001.com:7001/eureka

#请保存为UTF-8格式